version: '3.8'

services:
  query-optimizer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: query-optimizer
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    volumes:
      - ./credential/service-account.json:/app/service-account.json
    ports:
      - 8501:8501
    networks:
      - datadog

  datadog-agent:
    image: gcr.io/datadoghq/agent:latest
    container_name: datadog-agent
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=datadoghq.com
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - datadog

networks:
  datadog:
